import { jsPDF } from 'jspdf';
import { PatientData } from "../types/PatientData";

export const generatePDF = (patientData: PatientData) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Dr. D. Y. Patil Medical Hospital", 105, 20, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Sector 5, Akrudi, Pune - 411044 | Phone: +91-20-12345678", 105, 28, { align: "center" });
  doc.text("Outpatient Department (OPD) Case Paper", 105, 36, { align: "center" });

  // Separator
  doc.setLineWidth(0.5);
  doc.line(20, 40, 190, 40);

  // Patient Details
  doc.setFont("helvetica", "bold");
  doc.text("Patient Details", 20, 50);
  doc.setFont("helvetica", "normal");

  doc.text(`Record ID         : ${patientData.id}`, 20, 60);
  doc.text(`Full Name         : ${patientData.FullName}`, 20, 68);
  doc.text(`Age / Gender      : ${patientData.Age} / ${patientData.Gender}`, 20, 76);
  doc.text(`Location          : ${patientData.Location}`, 20, 84);

  // Medical Info
  doc.setFont("helvetica", "bold");
  doc.text("Clinical Information", 20, 98);
  doc.setFont("helvetica", "normal");

  doc.text(`Medical History   : ${patientData.MedicalHistory.join(', ') || 'None'}`, 20, 108);
  doc.text(`Symptoms          : ${patientData.LikelySymptoms.join(', ') || 'None'}`, 20, 116);
  doc.text(`Likely Diseases   : ${patientData.LikelyDiseases.join(', ') || 'N/A'}`, 20, 124);
  doc.text(`Severity Level    : ${patientData.SeverityLevel}`, 20, 132);
  doc.text(`Urgency           : ${patientData.Urgency}`, 20, 140);

  // OPD Recommendation
  doc.setFont("helvetica", "bold");
  doc.text("Recommended Department", 20, 154);
  doc.setFont("helvetica", "normal");
  doc.text(`${patientData.RecommendedOPD}`, 30, 162);

  // Footer
  doc.setLineWidth(0.1);
  doc.line(20, 270, 190, 270);
  doc.setFontSize(10);
  doc.text("Generated by DYPMC OPD Automation System", 105, 276, { align: "center" });

  // Save
  doc.save(`${patientData.FullName}_CasePaper.pdf`);
};
